Repository JeffreyCHChan/SOEN390, pull requests merged in 2022-03, with the labels that each got.

#99 Doctor appointments
  client/package-lock.json
  client/public/1.png
  client/src/App.js
  client/src/__tests__/API_methods.test.js
  client/src/__tests__/PatientAppointment.test.js
  client/src/components/Navbar.js
  client/src/pages/Login.js
  client/src/pages/PatientAppointment.js
  client/src/pages/PatientProfile.js
  package-lock.json
  server/app.js
  server/appointments.js
  server/requests.rest
Labels: Priority 3, Front End, Back End

#145 Post to get fixes
  client/src/pages/DoctorDashboard.js
  server/Controllers/DoctorController.js
  server/package-lock.json
Labels: Back End

#155 Live chat feature
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__tests__/API_methods.test.js
  client/src/__tests__/LiveChatDoctor.test.js
  client/src/__tests__/LiveChatPatient.test.js
  client/src/pages/DoctorViewingPatient.js
  client/src/pages/LiveChatDoctor.js
  client/src/pages/LiveChatPatient.js
  client/src/pages/PatientProfile.js
  server/Controllers/ChatController.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: Priority 1, Front End, Back End

#157 autofill patient info & urgent request
  client/src/App.js
  client/src/__tests__/API_methods.test.js
  client/src/pages/DoctorFileDownload.js
  client/src/pages/DoctorViewingPatient.js
  client/src/pages/EditInfoForm.js
  client/src/pages/PatientFiles.js
  client/src/pages/PatientProfile.js
  client/src/pages/SymptomForm.js
  server/.env
  server/Controllers/PatientController.js
Labels: Priority 2, Front End, Back End
